version: "3"

services:
    next-app:
        container_name: FE_FCodeTest
        build:
            context: ./
            target: runner
            dockerfile: Dockerfile
        restart: always
        ports:
            - 3001:3001
        env_file:
            - .env.local
        environment:
            - NODE_ENV=production
        networks:
            - default
